# .nosana-ci.yml
nosana:
  description: Nosana Deno Template

global:

  # Git, trigger on these branches
  trigger:
    branch:
      - main

  # Environment variables
  environment:
    APP_ENV: production  # comment here about this var

jobs:
  # Init Deno
  - name: install
    commands:
      - env
      - ls -lah
      - pwd